// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVKqW40xdlgq6W50ndG_AfhvNZEdBz2o4',
    appId: '1:579131205390:web:4d9ca083b15376e675d95f',
    messagingSenderId: '579131205390',
    projectId: 'mentorloop-21e1e',
    authDomain: 'mentorloop-21e1e.firebaseapp.com',
    storageBucket: 'mentorloop-21e1e.firebasestorage.app',
    measurementId: 'G-H8QTYJ366X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARC4rlaDslfCGJbsX5zn05Wb8t6hGMJ6c',
    appId: '1:579131205390:android:a249cc646199a12775d95f',
    messagingSenderId: '579131205390',
    projectId: 'mentorloop-21e1e',
    storageBucket: 'mentorloop-21e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5LhdqwRHCJipjuNplHDzi81cwdTfwbNE',
    appId: '1:579131205390:ios:4a242d0ff56d007d75d95f',
    messagingSenderId: '579131205390',
    projectId: 'mentorloop-21e1e',
    storageBucket: 'mentorloop-21e1e.firebasestorage.app',
    iosBundleId: 'com.example.mentorloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5LhdqwRHCJipjuNplHDzi81cwdTfwbNE',
    appId: '1:579131205390:ios:4a242d0ff56d007d75d95f',
    messagingSenderId: '579131205390',
    projectId: 'mentorloop-21e1e',
    storageBucket: 'mentorloop-21e1e.firebasestorage.app',
    iosBundleId: 'com.example.mentorloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVKqW40xdlgq6W50ndG_AfhvNZEdBz2o4',
    appId: '1:579131205390:web:c2ea0fa913516e1e75d95f',
    messagingSenderId: '579131205390',
    projectId: 'mentorloop-21e1e',
    authDomain: 'mentorloop-21e1e.firebaseapp.com',
    storageBucket: 'mentorloop-21e1e.firebasestorage.app',
    measurementId: 'G-708EW0GNV2',
  );
}
